remark: This is a config file for training VAE model.
dataset: human-body2
template: template2.ply
model_name: vae_coma
batch_size: 64
ds_factor:
- 4
- 4
- 4
- 4
model:
  latent_channels: 8
  in_channels: 3
  out_channels:
  - 16
  - 16
  - 16
  - 32
  K: 6
lr: 0.0001
weight_decay: 0
betas: (0.9, 0.999)
trainer: vanilla_vae
epochs: 300
reduce: sum
out_dir: /home/yuhao/Desktop/VAE/out/vanilla_vae/20230829-104825
