from .Trainer1 import Trainer1
from .Trainer2 import Trainer2
from .Trainer3 import Trainer3
from .Trainer4 import Trainer4
from .Trainer5 import Trainer5
from .Trainer6 import Trainer6
from .Trainer7 import Trainer7
from .Trainer8 import Trainer8
from .Trainer9 import Trainer9
from .Trainer10 import Trainer10
from .Trainer11 import Trainer11
from .Trainer12 import Trainer12
from .Trainer13 import Trainer13
from .Trainer14 import Trainer14
from .Trainer15 import Trainer15
from .Trainer16 import Trainer16